config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :ads
  end
end

app/models/spree/ad.rb
module Spree
  class Ad < ActiveRecord::Base
    attr_accessible :name, :file_name, :url, :width, :height, :position, :tag, :enabled
  end
end

app/controllers/spree/admin/ads_controller.rb
# encoding: utf-8
module Spree
  module Admin
    class AdsController < Admin::ResourceController

      POSITIONS = [['Choose location...', 0], ['Home sidebar left', 1], ['Home sidebar right', 2], ['All sidebar left', 3], ['All sidebar right', 4], ['Home Slider', 5]]

      def index
        @ads = Spree::Ad.page(params[:page]).per(params[:per_page] || Spree::Config[:orders_per_page])
        @position_types = POSITIONS
      end

      def new
        @ad = Spree::Ad.new
        @ad.save(validate: false)
        redirect_to edit_admin_ad_url(@ad)
      end

      def edit
        @ad = Spree::Ad.find(params[:id])
        @position_types = POSITIONS
      end

      def update
        @ad = Spree::Ad.find(params[:id])
        if params[:ad][:file_name]
          uploaded_io = params[:ad][:file_name]
          new_file_name = uploaded_io.original_filename.gsub(' ','')

          File.open(Rails.root.join('public', 'ads', new_file_name), 'wb') do |file|
            file.write(uploaded_io.read)
          end
          @ad.file_name = new_file_name
        end

        @ad.name = params[:ad][:name]
        @ad.url = params[:ad][:url]
        @ad.width = params[:ad][:width]
        @ad.height = params[:ad][:height]

        @ad.position = params[:ad][:position]
        @ad.tag = params[:ad][:tag]
        @ad.enabled = params[:ad][:enabled]

        if @ad.save
          redirect_to admin_ads_path, notice: 'Updated!'
        else
          render :action => :edit
        end
      end

      def destroy
        ad = Spree::Ad.find(params[:id])

        if ad.file_name != nil
          File.unlink(Rails.root.join('public', 'ads', ad.file_name))
        end

        if ad.destroy
          redirect_to admin_ads_path, notice: 'Deleted!'
        else
          redirect_to admin_ads_path
        end
      end

    end
  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelper

    def ad_code(ad)
      if ad.file_name =~ /\.swf/
        if ad.position == 5
          result = <<-eos
            <embed type="application/x-shockwave-flash" src="/ads/#{ad.file_name}" width="600" height="200" style="undefined" id="ad-#{ad.id}" name="#{ad.name}" quality="high" allowscriptaccess="always">
          eos
        else
          result = <<-eos
            <embed type="application/x-shockwave-flash" src="/ads/#{ad.file_name}" width="#{(ad.width if ad.width)}" height="#{(ad.height if ad.height)}" style="undefined" id="ad-#{ad.id}" name="#{ad.name}" quality="high" allowscriptaccess="always">
          eos
        end
      else
        if ad.position == 5
          result = <<-eos
            <a href="#{ad.url}" target="_blank"><img src="/ads/#{ad.file_name}" alt="#{ad.name}" width="600" height="200"></a>
          eos
        else
          result = <<-eos
            <a href="#{ad.url}" target="_blank"><img src="/ads/#{ad.file_name}" alt="#{ad.name}" width="#{ad.width}" height="#{ad.height}"></a>
          eos
        end
      end
      return result.html_safe
    end

  end
end

app/views/spree/admin/ads/_form.html.erb
<div data-hook="admin_ad_form_fields">

  <div class="left seven columns alpha" data-hook="admin_product_form_left">    
    <%= f.field_container :name do %>
      <%= f.label :name, raw(Spree.t(:name)) %>
      <%= f.text_field :name, :class => 'fullwidth name' %>
      <%= f.error_message_on :name %>
    <% end %>

    <%= f.field_container :url do %>
      <%= f.label :url, raw(Spree.t(:url)) %><br>
      <small><%= Spree.t(:only_image_html) %></small>
      <%= f.text_field :url, :class => 'fullwidth url' %>
      <%= f.error_message_on :url %>
    <% end %>

    <div class="ad_size">
      <%= f.field_container :width do %>
        <%= f.label :width, raw(Spree.t(:width)) %><br>
        <%= f.text_field :width, :class => 'fullwidth width' %>
        <%= f.error_message_on :width %>
      <% end %>

      <%= f.field_container :height do %>
        <%= f.label :height, raw(Spree.t(:height)) %><br>
        <%= f.text_field :height, :class => 'fullwidth height' %>
        <%= f.error_message_on :height %>
      <% end %>
    </div>
  </div>

  <div class="center two columns alpha">&nbsp;</div>

  <div class="right seven columns alpha" data-hook="admin_product_form_left">    
    <% if @ad.file_name %>
      <br>
      <%= link_to 'Show Ad', '/ads/' + @ad.file_name, :target => '_blank', :class => 'button' %>&nbsp;
      <strong><%= Spree.t(:current_ad) %>:</strong> <%= @ad.file_name %>
    <% end %>
    <hr>
    <%= f.field_container :file_name do %>
      <%= f.label :file_name, raw(Spree.t(:file_name)) %>
      <%= f.file_field :file_name, :class => 'fullwidth file_name' %>
      <%= f.error_message_on :file_name %>
    <% end %>
    <br><br>

    <%= f.field_container :position do %>
      <%= f.label :position, raw(Spree.t(:position)) %>
      <%= f.select :position, @position_types, {}, :class => 'fullwidth position' %>
      <%= f.error_message_on :position %>
    <% end %>

    <%= f.field_container :tag do %>
      <%= f.label :tag, raw(Spree.t(:tag)) %><br>
      <small><%= Spree.t(:tag_notice) %></small>
      <%= f.text_field :tag, :class => 'fullwidth tag' %>
      <%= f.error_message_on :tag %>
    <% end %>

    <%= f.field_container :enabled do %>
      <%= f.label :enabled, raw(Spree.t(:enabled)) %>
      <%= f.check_box :enabled, :class => 'enabled' %>
      <%= f.error_message_on :enabled %>
    <% end %>
  </div>
  <div class="clear"></div>
 
  <br>
  <hr> 
  <%= f.field_container :submit do %>
    <%= f.submit 'Save', :class => 'enabled' %>
  <% end %>

</div>

<script>
(function($) {
  if($('select.position').val() == 5){
    $('.ad_size').hide();
  }

  $('select.position').change(function(){
    if($(this).val() == 5){ 
      $('.ad_size').hide();
    } else {
      $('.ad_size').show();
    }
  });
})(jQuery);
</script>

app/views/spree/admin/ads/edit.html.erb
<%= csrf_meta_tags %>

<% content_for :page_title do %>
  <%= Spree.t(:edit_ad) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:admin, Spree::Order) %>
    <li><%= button_link_to Spree.t(:back_to_ads_listing), admin_ads_path, :icon => 'icon-arrow-left' %></li>
  <% end %>
<% end %>

<div data-hook="admin_ads_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @ad } %>
</div>

<div data-hook="admin_ad_edit_form">
  <%= form_for [:admin, @ad], :method => :put, :html => { :multipart => true } do |f| %>
    <div id="ad-form-wrapper">
      <%= render :partial => 'form', :locals => { :f => f } %>
    </div>
  <% end %>
</div>

app/views/spree/admin/ads/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:listing_ads) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_ad), new_admin_ad_url, :icon => 'icon-plus', :id => 'admin_new_ad' %>
  </li>
<% end if can? :edit, Spree::Ad.new %>

<%= paginate @ads %>

<% if @ads.any? %>
  <table class="index responsive" id="listing_ads" data-hook>
    <colgroup>
       <col style="width: 5%;">
       <col style="width: 15%;">
       <col style="width: 35%;">
       <col style="width: 30%;">
       <col style="width: 5%;">
       <col style="width: 10%;">
       <col style="width: 5%;">
    </colgroup>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <th><%= Spree.t(:created_at, resource: I18n.t(:other, scope: 'activerecord.models.spree/ad')) %></th>
        <th><%= Spree.t(:position, resource: I18n.t(:other, scope: 'activerecord.models.spree/ad')) %></th>
        <th><%= Spree.t(:name, resource: I18n.t(:other, scope: 'activerecord.models.spree/ad')) %></th>
        <th><%= Spree.t(:file_name, resource: I18n.t(:other, scope: 'activerecord.models.spree/ad')) %></th>
        <th><%= Spree.t(:enabled, resource: I18n.t(:other, scope: 'activerecord.models.spree/ad')) %></th>
    </thead>
    <tbody>
    <% @ads.each do |ad| %>
      <tr data-hook="admin_ads_index_rows" class="state-<%= ad.enabled %> <%= cycle('odd', 'even') %>">
        <td class="align-center"><%= ad.created_at.strftime('%d.%m.%Y') %></td>
        <td class="align-center"><%= @position_types[ad.position][0] %></td>
        <td class="align-center"><%= link_to ad.name, edit_admin_ad_path(ad) %></td>
        <td class="align-center"><%= ad.file_name %></td>
        <td class="align-center"><%= ad.enabled %></td>
        <td class="align-center">
          <%= link_to 'Show', '/ads/' + ad.file_name, :target => '_blank', :class => 'button' if ad.file_name %>
        </td>
        <td class='actions align-center' data-hook="admin_ads_index_row_actions">
          <%= link_to_edit_url edit_admin_ad_path(ad), :title => "admin_edit_#{dom_id(ad)}", :no_text => true %>
          <%= link_to_delete ad, :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alpha twelve columns no-objects-found">
    <%= Spree.t(:no_resource_found, resource: I18n.t(:other, scope: 'activerecord.models.spree/ad')) %>,
    <%= link_to Spree.t(:add_one), spree.new_admin_ad_path %>!
  </div>
<% end %>

<%= paginate @ads %>

app/views/spree/shared/ads/_all_sidebar_left.html.erb
<h1>All Sidebar Left</h1>
<% Spree::Ad.where(:position => 3).each do |ad| %>
  <%= ad_code(ad) %>
<% end %>

app/views/spree/shared/ads/_all_sidebar_right.html.erb
<h1>All Sidebar Right</h1>
<% Spree::Ad.where(:position => 4).each do |ad| %>
  <%= ad_code(ad) %>
<% end %>

app/views/spree/shared/ads/_home_sidebar_left.html.erb
<h1>Home Sidebar Left</h1>
<% Spree::Ad.where(:position => 1).each do |ad| %>
  <%= ad_code(ad) %>
<% end %>

app/views/spree/shared/ads/_home_sidebar_right.html.erb
<h1>Home Sidebar Right</h1>
<% Spree::Ad.where(:position => 2).each do |ad| %>
  <%= ad_code(ad) %>
<% end %>

app/views/spree/shared/ads/_home_slider.html.erb
<h1>Slider</h1>
<% Spree::Ad.where(:position => 5).each do |ad| %>
  <%= ad_code(ad) %>
<% end %>